[tox]
envlist = py{37,38,39,310,311,312}-django{22,32,40,50}
isolated_build = True

[testenv]
deps =
    django22: Django>=2.2,<3.0
    django32: Django>=3.2,<4.0
    django40: Django>=4.0,<5.0
    django50: Django>=5.0,<6.0
    pytest
    pytest-django
commands = pytest tests/
